- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for writing smoke test.
    uri:
      url: http://localhost/index.html
      return_content: yes
    register: site
    failed_when: "'Ansible has done its job' is not in the site.content"
